In [0]:
import dask.array as da

In [0]:
import numpy as np

## Dask Arrays


In [0]:
a=np.arange(20)
dask_a=da.from_array(a,chunks=len(a)//4)

In [9]:
dask_a.shape

(20,)

In [10]:
dask_a.mean(axis=0).compute()

9.5

## HDF5 Files

* hdf5 is a heirarchial format fo storing and managing data

In [0]:
import h5py

In [0]:
# open a HDF5 file object

data_store=h5py.File('Texas/texas.2014.hdf5')

In [15]:
type(data_store)

h5py._hl.files.File

In [18]:
for key in data_store.keys():
  print(key)

load


In [0]:
data=data_store['load']

In [21]:
type(data)

h5py._hl.dataset.Dataset

In [22]:
data.shape

(35040,)

In [0]:
dask_data=da.from_array(data,chunks=len(data)//7)

In [25]:
dask_data.min().compute()

3832.260999999999

In [27]:
da.nanmin(dask_data).compute()

3832.260999999999

## Stacking Arrays

In [0]:
a=np.arange(1,10)
b=np.arange(2,11)

In [29]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
np.hstack([a,b])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  2,  3,  4,  5,  6,  7,  8,  9,
       10])

In [35]:
np.vstack([a,b])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [0]:
a=da.from_array(a,chunks=len(a)//4)
b=da.from_array(b,chunks=len(a)//4)

In [40]:
da.hstack([a,b])

dask.array<concatenate, shape=(18,), dtype=int64, chunksize=(2,), chunktype=numpy.ndarray>

In [41]:
da.vstack([a,b]) #its so pretty wtf

dask.array<concatenate, shape=(2, 9), dtype=int64, chunksize=(1, 2), chunktype=numpy.ndarray>